using PullSight.Api.Contracts.Reviews;

namespace PullSight.Api.Services.ReviewAnalysis;

public sealed class RuleBasedCodeReviewAnalyzer : ICodeReviewAnalyzer
{
    public Task<ReviewRunResponse> AnalyzeDemoAsync(CancellationToken cancellationToken)
    {
        var findings = new List<ReviewFindingResponse>
        {
            new(
                "rule_auth_001",
                "high",
                "src/Controllers/DiscountsController.cs",
                74,
                "Admin discount override endpoint is missing authorization",
                "The endpoint mutates discount rules but does not require an Admin policy.",
                "rule"),
            new(
                "rule_sql_001",
                "medium",
                "src/Data/PromotionRepository.cs",
                53,
                "Raw SQL filter builds a dynamic sort clause",
                "Dynamic query fragments should be validated against an allow-list before execution.",
                "rule"),
        };

        var response = new ReviewRunResponse(
            "demo_run_001",
            "commerce-api",
            42,
            "a18f92d",
            "fallback",
            "RuleBasedCodeReviewAnalyzer",
            72,
            5,
            "Demo review generated by the backend fallback analyzer skeleton.",
            findings);

        return Task.FromResult(response);
    }
}
